# Gets the FTP deployment credentials for the given app service
parameters:
  environmentSubscription: ''
  resourceName: ''
  resourceGroupName: ''
  deploymentSlotName: ''
  ftpUrlOutputVariableName: ''
  ftpUsernameOutputVariableName: ''
  ftpPasswordOutputVariableName: ''

steps:
  - task: AzureCLI@2
    displayName: 'Get FTP Deployment Credentials - ${{parameters.resourceName}}'
    inputs: 
      azureSubscription: ${{parameters.environmentSubscription}}
      scriptType: ps
      scriptLocation: inlineScript
      inlineScript: |
        $credentials = az webapp deployment list-publishing-profiles --name ${{parameters.resourceName}} --resource-group ${{parameters.resourceGroupName}} --slot ${{parameters.deploymentSlotName}} --query "[?publishMethod=='FTP'].{PublishUrl:publishUrl, Username:userName, Password:userPWD}" | ConvertFrom-Json
        $ftpUrl = $credentials.PublishUrl
        $ftpUsername = $credentials.Username
        $ftpPassword = $credentials.Password
        Write-Host "##vso[task.setvariable variable=${{parameters.ftpUrlOutputVariableName}}]$ftpUrl"
        Write-Host "##vso[task.setvariable variable=${{parameters.ftpUsernameOutputVariableName}}]$ftpUsername"
        Write-Host "##vso[task.setvariable variable=${{parameters.ftpPasswordOutputVariableName}};issecret=true]$ftpPassword"